name: jlab-mxf
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - conda-forge
  - plotly
dependencies:
  - python>=3.10,<3.12
  - ruff
  - numpy
  - pandas
  - polars
  - numba
  - sympy
  - unyt
  - networkx
  - scipy
  - scikit-learn
  - scikit-learn-intelex
  - scikit-image
  - jupyter
  - xeus-python
  - jupyterlab
  - jupyterlab-favorites
  - jupyterlab-recents
  - jupytext
  - jupyterlab-plotly-extension
  - jupyterlab-geojson
  - jupyterlab-mathjax3
  - jupyterlab-katex
  - ripgrep
  - jupyterlab-search-replace 
  - jupyterlab_commands
  - jupyterlab_code_formatter
  - black
  - isort
  - nb_black
  - ipympl
  - jupyter-archive
  - theme-darcula 
  - jupyterlab_pygments
  - ipywidgets
  - ipydatagrid
  - ipycanvas
  - ipycytoscape
  - ipytree
  - ipyfilechooser
  - ipyvue
  - ipyvuetify
  - reacton
  - watchdog
  - plotly
  - python-kaleido
  - plotly-geo
  - vegafusion-jupyter
  - vegafusion
  - vegafusion-python-embed
  - python-duckdb
  - palettable
  - altair
  - vega_datasets
  - pillow
  - seaborn
  - voila
  - openpyxl
  - xlsxwriter
  - xmltodict
  - pillow
  - jsonschema2md
  - quarto>1.7
  - r-tinytex
  - fluids
  - cmap
  - pip>=23,<24
  - pip:
    - ./site-packages/aecschedule-0.24.7.tar.gz
    - ./site-packages/aectemplater_client-0.24.7.tar.gz
    - ./site-packages/aectemplater_schemas-0.24.7.tar.gz
    - ./site-packages/aectemplater_ui-0.24.7.tar.gz
    - ./site-packages/aecreference-0.24.7.tar.gz
    - ./site-packages/pyrulefilter-0.24.7.tar.gz
    - ./site-packages/mfdb-0.24.7.tar.gz
    - ./site-packages/netzero_metrics-0.24.7.tar.gz
    - jupyterlab-quarto
    - seedir
    - emoji
    - mosaic-widget
    - ipyautoui >=0.7,<0.8
    - ipyrun >=0.6,<0.7
    - git+https://git@github.com/maxfordham/xlsxdatagrid.git@0.1.2
    - git+https://git@github.com/maxfordham/document-issue.git@0.8.4#subdirectory=packages/document-issue
    - git+https://git@github.com/maxfordham/document-issue.git@0.8.4#subdirectory=packages/document-issue-io
